package com.tfsla.diario.newsletters.common.strings;

public class SqlQueries {
	public static final String GET_NEWSLETTERS = "SELECT * FROM TFS_NEWSLETTER";
	public static final String GET_NEWSLETTER_BY_ID = GET_NEWSLETTERS + " WHERE REGISTER_ID = ?";
	public static final String GET_EMAILS_SUBSCRIBED_TO_NEWSLETTER = "SELECT EMAIL FROM TFS_NEWSLETTER_SUBSCRIPTION WHERE NEWSLETTER_ID = ? AND STATUS = 1";
	public static final String GET_EMAILS_SUBSCRIBED_TO_NEWSLETTER_PAGED = "SELECT EMAIL FROM TFS_NEWSLETTER_SUBSCRIPTION WHERE NEWSLETTER_ID = ? AND STATUS = 1 ORDER BY REGISTER_ID LIMIT ?, ?";
	public static final String GET_COMPLAINT_TYPES = "SELECT * FROM TFS_NEWSLETTER_COMPLAINT_TYPES";
	public static final String GET_COMPLAINT_TYPES_ORDER = " ORDER BY IS_COMPLAINT ASC, NAME ASC";
	public static final String GET_COMPLAINT_TYPE_BY_ID = GET_COMPLAINT_TYPES + " WHERE REGISTER_ID = ?";
	public static final String GET_SUBSCRIBED_TO_NEWSLETTER = "SELECT * FROM TFS_NEWSLETTER_SUBSCRIPTION WHERE NEWSLETTER_ID = ? AND STATUS = 1";
	public static final String GET_SUBSCRIBERS = "SELECT * FROM TFS_NEWSLETTER_SUBSCRIPTION WHERE 1 = 1";
	public static final String GET_NEWSLETTER_SUBSCRIPTOR = "SELECT * FROM TFS_NEWSLETTER_SUBSCRIPTION WHERE NEWSLETTER_ID = ? AND EMAIL = ?";
	public static final String GET_NEWSLETTER_SUBSCRIPTORS = "SELECT COUNT(*) AS SUBSCRIPTORS FROM TFS_NEWSLETTER_SUBSCRIPTION WHERE NEWSLETTER_ID = ? AND STATUS = 1";
	public static final String GET_NEWSLETTER_DISPATCHES = "SELECT * FROM TFS_NEWSLETTER_DISPATCH WHERE NEWSLETTER_ID = ?";
	public static final String GET_NEWSLETTER_DISPATCHES_COUNT = "SELECT SUM(MAILS_SENT) AS DISPATCHES FROM TFS_NEWSLETTER_DISPATCH WHERE NEWSLETTER_ID = ?";
	public static final String GET_NEWSLETTER_EVENTS_BY_DATE = "SELECT COUNT(REGISTER_ID) AS EVENTS_COUNT, DATE(EVENT_DATE) AS DATE_EVENT, EVENT_TYPE FROM TFS_NEWSLETTER_EVENT WHERE EVENT_DATE > ? %s GROUP BY DATE_EVENT, EVENT_TYPE ORDER BY DATE_EVENT ASC";
	public static final String GET_NEWSLETTER_EVENTS_BY_MONTH = "SELECT COUNT(REGISTER_ID) AS EVENTS_COUNT, MAKEDATE(YEAR(EVENT_DATE), MONTH(EVENT_DATE)) AS DATE_EVENT, EVENT_TYPE FROM TFS_NEWSLETTER_EVENT WHERE EVENT_DATE > ? %s GROUP BY DATE_EVENT, EVENT_TYPE ORDER BY DATE_EVENT ASC";
	public static final String GET_NEWSLETTER_SUBSCRIPTIONS_BY_DATE = "SELECT COUNT(REGISTER_ID) AS USERS_COUNT, DATE(SUBSCRIBED_DATE) AS DATE_EVENT FROM TFS_NEWSLETTER_SUBSCRIPTION WHERE SUBSCRIBED_DATE > ? AND STATUS = 1 %s GROUP BY DATE_EVENT ORDER BY DATE_EVENT ASC";
	public static final String GET_NEWSLETTER_SUBSCRIPTIONS_BY_MONTH = "SELECT COUNT(REGISTER_ID) AS USERS_COUNT, MAKEDATE(YEAR(SUBSCRIBED_DATE), MONTH(SUBSCRIBED_DATE)) AS DATE_EVENT FROM TFS_NEWSLETTER_SUBSCRIPTION WHERE SUBSCRIBED_DATE > ? AND STATUS = 1 %s GROUP BY DATE_EVENT ORDER BY DATE_EVENT ASC";
	public static final String GET_NEWSLETTER_SUBSCRIBERS_UP_TO_DATE = "SELECT COUNT(REGISTER_ID) AS USERS_COUNT FROM TFS_NEWSLETTER_SUBSCRIPTION WHERE SUBSCRIBED_DATE <= ?";
	public static final String GET_NEWSLETTER_PERFORMANCE = "SELECT SUM(MAILS_SENT) AS SENT FROM TFS_NEWSLETTER_DISPATCH WHERE DISPATCH_DATE > ?";
	public static final String GET_NEWSLETTER_PERFORMANCE_FILTERED = "SELECT SUM(MAILS_SENT) AS SENT FROM TFS_NEWSLETTER_DISPATCH WHERE DISPATCH_DATE > ? AND NEWSLETTER_ID = ?";
	public static final String GET_AUDIENCE_FROM_DATE = "SELECT COUNT(REGISTER_ID) AS USERS_COUNT, STATUS FROM TFS_NEWSLETTER_SUBSCRIPTION WHERE SUBSCRIBED_DATE > ? %s GROUP BY STATUS";
	public static final String GET_NEWSLETTER_LOSTS_BY_DATE = "SELECT COUNT(REGISTER_ID) AS USERS_COUNT, DATE(UPDATED_DATE) AS DATE_EVENT FROM TFS_NEWSLETTER_SUBSCRIPTION WHERE UPDATED_DATE > ? AND STATUS = 0 %s GROUP BY DATE_EVENT ORDER BY DATE_EVENT ASC";
	public static final String GET_NEWSLETTER_LOSTS_BY_MONTH = "SELECT COUNT(REGISTER_ID) AS USERS_COUNT, MAKEDATE(YEAR(UPDATED_DATE), MONTH(UPDATED_DATE)) AS DATE_EVENT FROM TFS_NEWSLETTER_SUBSCRIPTION WHERE UPDATED_DATE > ? AND STATUS = 0 %s GROUP BY DATE_EVENT ORDER BY DATE_EVENT ASC";
	public static final String UNSUBSCRIBE_FROM_NEWSLETTER = "UPDATE TFS_NEWSLETTER_SUBSCRIPTION SET STATUS = 0, UPDATED_DATE = ? WHERE EMAIL = ? AND NEWSLETTER_ID = ?";
	public static final String UNSUBSCRIBE_EMAIL = "UPDATE TFS_NEWSLETTER_SUBSCRIPTION SET STATUS = 0, UPDATED_DATE = ? WHERE EMAIL = ?";
	public static final String SUBSCRIBE_TO_NEWSLETTER = "INSERT INTO TFS_NEWSLETTER_SUBSCRIPTION (EMAIL, NEWSLETTER_ID) VALUES (?, ?)";
	public static final String ADD_NEWSLETTER_DISPATCH = "INSERT INTO TFS_NEWSLETTER_DISPATCH (NEWSLETTER_ID, MAILS_SENT) VALUES (?, ?)";
	public static final String ADD_NEWSLETTER_EVENT = "INSERT INTO TFS_NEWSLETTER_EVENT (FROM_EMAIL, TO_EMAIL, EVENT_TYPE, EVENT_DATA, ELEMENT, NEWSLETTER_ID) VALUES (?, ?, ?, ?, ?, ?)";
	public static final String UPDATE_NEWSLETTER_SUBJECT = "UPDATE TFS_NEWSLETTER SET SUBJECT = ? WHERE REGISTER_ID = ?";
	public static final String UPDATE_NEWSLETTER_SUBSCRIPTION = "UPDATE TFS_NEWSLETTER_SUBSCRIPTION SET STATUS = ?, UPDATED_DATE = ?, EMAIL = ? WHERE REGISTER_ID = ?";
	public static final String UPDATE_NEWSLETTER_SUBSCRIPTION_COMPLAINT = "UPDATE TFS_NEWSLETTER_SUBSCRIPTION SET COMPLAINT_ID = ? WHERE REGISTER_ID = ?";
	public static final String ADD_NEWSLETTER_COMPLAINT = "INSERT INTO TFS_NEWSLETTER_COMPLAINTS (SUBSCRIPTION_ID, COMPLAINT_ID, MESSAGE) VALUES (?, ?, ?)";
	
	public static final String PURGE_NEWSLETTER_EVENT = "DELETE FROM TFS_NEWSLETTER_EVENT WHERE EVENT_DATE < ? %s ";
	public static final String ADD_NEWSLETTER_EVENT_SUMMARY = "INSERT INTO TFS_NEWSLETTER_EVENT_SUMMARY (NEWSLETTER_ID,EVENT_TYPE,DAY_EVENT,EVENTS_COUNT) VALUES (?,?,?,1) ON DUPLICATE KEY UPDATE EVENTS_COUNT=EVENTS_COUNT+1";
	public static final String GET_NEWSLETTER_EVENTS_SUMMARY_BY_DATE = "SELECT SUM(EVENTS_COUNT) AS EVENTS_COUNT, DATE(DAY_EVENT) AS DATE_EVENT, EVENT_TYPE FROM TFS_NEWSLETTER_EVENT_SUMMARY WHERE DAY_EVENT > ? %s GROUP BY DAY_EVENT, EVENT_TYPE ORDER BY DATE_EVENT ASC";
	public static final String GET_NEWSLETTER_EVENTS_SUMMARY_BY_MONTH = "SELECT SUM(EVENTS_COUNT) AS EVENTS_COUNT, MAKEDATE(YEAR(DAY_EVENT), MONTH(DAY_EVENT)) AS DATE_EVENT, EVENT_TYPE FROM TFS_NEWSLETTER_EVENT_SUMMARY WHERE DAY_EVENT > ? %s GROUP BY DAY_EVENT, EVENT_TYPE ORDER BY DATE_EVENT ASC";

	
	
	public static final String FILTER_AND = " AND ";
	public static final String NEWSLETTER_FILTER = " NEWSLETTER_ID = ? ";
	public static final String EMAIL_FILTER = " EMAIL LIKE ? ";
	public static final String STATUS_FILTER = " STATUS = ? ";
	public static final String LIMIT = " LIMIT ? ";
	public static final String ORDER_BY = " ORDER BY ? ";
}
